### ISSUE TITLE
Driver initialize connection failed error: "'hostname'"

### ISSUE THREAD

**Issue by kumartin** [hp-storage/python-3parclient#14]
The following exception occurs when attempting to attach a volume to a 3PAR that has VLUNs with no hostnames. This could happen if volume or volume set were exported to direct ports. The client's getHostVluns needs to take this into account.

2015-05-12 13:22:12.859 ERROR cinder.volume.manager [req-ae836f09-b688-4803-b710-bbc2b46cef20 None None] (u'Driver initialize connection failed (error: %(err)s).', {'err': u"'hostname'"})
2015-05-12 13:22:12.861 ERROR oslo_messaging.rpc.dispatcher [req-ae836f09-b688-4803-b710-bbc2b46cef20 None None] Exception during message handling: Bad or unexpected response from the storage volume backend API: (u'Driver initialize connection failed (error: %(err)s).', {'err': u"'hostname'"})
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher Traceback (most recent call last):
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatc
her.py", line 142, in _dispatch_and_reply
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher     executor_callback))
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 186, in _dispatch
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher     executor_callback)
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher     result = func(ctxt, **new_args)
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/osprofiler/profiler.py", line 105, in wrapper
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher     return f(*args, **kwargs)
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/osprofiler/profiler.py", line 105, in wrapper
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher     return f(*args, **kwargs)
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/osprofiler/profiler.py", line 105, in wrapper
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher     return f(*args, **kwargs)
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher   File "/opt/stack/cinder/cinder/volume/manager.py", line 1106, in initialize_connection
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher     raise exception.VolumeBackendAPIException(data=err_msg)
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: (u'Driver initialize connection failed (error: %(err)s).', {'err': u"'hostname'"})
2015-05-12 13:22:12.861 TRACE oslo_messaging.rpc.dispatcher
2015-05-12 13:22:12.876 ERROR oslo_messaging._drivers.common [req-ae836f09-b688-4803-b710-bbc2b46cef20 None None] Returning exception Bad or unexpected response from the storage volume backend API: (u'Driver initialize connection failed (error: %(err)s).', {'err': u"'hostname'"}) to caller

**Comment by hp-storage** [comment]
Fixed in 3.2.1 version
